# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-22debc83-c7d8-4427-92c3-dd7ba938b348";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-22debc83-c7d8-4427-92c3-dd7ba938b348".device = "/dev/disk/by-uuid/22debc83-c7d8-4427-92c3-dd7ba938b348";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9052-E0E3";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-571f74f6-94b2-47c8-abb2-2bd64c43b11f"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
